Support for Python < 2.7
Python 2.6.6 shipped with RHEL 6 does not support iter and displays the error:
UTILIZATION UNKNOWN: AttributeError: _ElementInterface instance has no attribute 'iter'
As a workaround "getiterator" will be used if the attribute "iter" is unkown

getiterator is deprecated since version 2.7 and was replaced by iter.

This patch adds support for Python < 2.7